version: "3.7"
services:
  rabbit:
    image: netsage/rabbitmq:3-management
    env_file: .env
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
  importer:
    image: netsage/pipeline_importer:latest
    env_file: .env
    depends_on:
      - rabbit
    restart: always
    volumes:
      - ./data:/data
      - ./data/importer_cache:/var/cache/netsage
      - ./conf-logstash:/usr/share/logstash/pipeline/
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.dataUpdate.schedule: "@weekly"
      ofelia.job-exec.dataUpdate.command: "/tmp/docker_init.sh"
  logstash:
    image: netsage/pipeline_logstash:latest
    networks:
      - netsage_pipeline
    external_links:
      - rabbit
    env_file: .env
    # entrypoint: sleep
    # command: "999999"
    depends_on:
      - rabbit
    volumes:
      - ./conf-logstash:/usr/share/logstash/pipeline/
      - ./data:/data
      - ./data/cache:/var/lib/grnoc/netsage/
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.dataUpdate.schedule: "@every 24h"
      ofelia.job-exec.dataUpdate.command: "/tmp/docker_init.sh"
  rabbit:
    image: netsage/rabbitmq:3-management
    env_file: .env
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq
    networks:
      - netsage_pipeline
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
  ofelia: ## Scheduler Task
    image: mcuadros/ofelia:v0.3.0
    command: daemon --docker
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  netsage_pipeline:
    name: netsage_pipeline
    # use a custom driver, with no options
    driver: bridge
