version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    env_file: .env
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.6.2
    env_file: .env
    restart: always
    ports:
      - "5601:5601"
