version: "3.7"
services:
   logstash:
      image: netsage/pipeline_logstash:latest
      build:
         context: .
         dockerfile: ./compose/logstash/Dockerfile
   filebeat:
      image: netsage/pipeline_filebeat:latest
      build:
         context: .
         dockerfile: ./compose/filebeat/Dockerfile
