version: "3.7"
services:

  logstash:
    image: netsage/pipeline_logstash:latest
  ## If you need to allocate more than 1GB (default) override the JMV options
  #    volumes:
  #      - ./userConfig/jvm.options:/usr/share/logstash/config/jvm.options

  importer:
    image: netsage/pipeline_importer:latest
  ## If you add additional collectors, you need to uncomment the following line and modify the file to add additional collections
  #   volumes:
  #      - ./userConfig/netsage_override.xml:/etc/grnoc/netsage/deidentifier/netsage_shared.xml

  ## Add any additional collectors here.  You may remove any collectors that are not needed.
  sflow-collector:
    image: netsage/nfdump-collector:alpine-1.6.23
    restart: always
    command: sfcapd -T all -l /data -S 1 -w -z -p 9998
    volumes:
      - ./data/input_data/sflow:/data
    ports:
      - "9998:9998/udp"
  netflow-collector:
    image: netsage/nfdump-collector:alpine-1.6.23
    command: nfcapd -T all -l /data -S 1 -w -z -p 9999
    ports:
      - "9999:9999/udp"
    restart: always
    volumes:
      - ./data/input_data/netflow:/data
